//all the textual data from pages

export const configuration = {
    header: {
        heading: '"Smart", "Sustainable", "Green"',
        headingtext: 'A Smarter Way To Manage Waste',
        headingbutton: 'DISCOVER',
        buttonlink: '/Intro'
    },
    intro: {
        heading: 'INTRO',
        headingtwo: 'We Are Here To Clean-Up The City',
        para: '“Fohor Malai” project aims to bridge the gap between these authorities and the households of the capital. Furthermore, the goal is to make recycling a norm and help our streets be free of waste all whilst making a positive change to our environment.Using devices such as the ultrasonic sensor we can measure the waste level and then use the GPS sensor to track the precise location allowing responsible organizations to timely gather the waste and recycle.',
        aim: 'This project will ensure the propoer collection and management of waste.',
        creator: 'Prabin Thapaliya - Creator',
        costtitle: 'Cost Reduction',
        costcontent: 'Thanks to the collaboration with the municipality, we can offer you much better rates to keep the town clean.',
        cleantitle: 'Clean',
        cleancontent: 'This system will surely get rid of unsanitary disposals and help keep your surroundings clean.',
        efficienttitle: 'Efficient',
        efficientcontent: 'Gathering waste has never been more efficient, thanks to the constant data provided by the sensors.'

    },
    services: {
        title: 'SERVICES',
        secondary: 'That Suit Your Needs',

        institle: 'Installation',
        inscontent: 'System installation with proper integration of hardware and software.',
        inspoint1: 'Trashcan Equipped With Sensors.',
        inspoint2: 'Web Application Authorization.',
        starting: 'Starting at ',
        inscost: 'Rs. 15,000',
        insdetails: 'DETAILS',
        button: 'btn-solid-reg page-scroll',

        teatitle: 'Teach the System',
        teacontent: 'We help interested people understand the system better and also the need for it.',
        teapoint1: 'Workings of the Hardware.',
        teapoint2: 'Workings of the Software.',
        teacost: 'Rs. 1,000',
        teadetails: 'DETAILS',

        wrktitle: 'Workshops',
        wrkcontent: 'We are also open to doing workshops and training programs in colleges.',
        wrkpoint1: 'Ideas to tackle climate change.',
        wrkpoint2: 'Classes on sustainability.',
        wrkcost: 'Free of Charge',
        wrkdetails: 'DETAILS',
    },
    system: {
        header: 'Cleaning the Country, one city at a time!',
        num1: '1',
        pointone: 'How Fohor Malai can help clean your city!',
        contentone: 'As firm believers in Smart Sustainability, we are here to use our knowledge in computer science and climate to ensure timely collection and disposal of waste in your city.',
        num2: '2',
        pointtwo: 'Reuse, Reduce, and Recycle',
        contenttwo: 'With plans to collaborate with companies like Doko Recyclers and Khaalisisi, we hope to inspire a generation to change their consumption habits.',
        num3: '3',
        pointthree: 'Campaigns for Awareness',
        contentthree: 'We offer interactive workshops and on-site tours for a range of audiences from children to policy-makers to educate, inform, and encourage action towards improving Nepal’s waste disposal practices.',

        city: 'City',
        cityservices: 'Services For Cities',
        citydetails: 'Fohor Malai is mainly focused on delivering quality hardware to manage waste in Kathmandu. We hope to reach the local waste management authorities to ',
        bridge: 'bridge the gap ',
        area: 'in your area.',
        graph1: 'Business Development 100%',
        graph2: 'Opportunity Spotting 76%',
        graph3: 'Online Marketing 90%',
        

        business: 'Business',
        pointnum1: '1',
        point1: 'Sustainability',
        point1content: ' is one of our major concerns as We help companies grow by helping them create and sustain positive environmental impact.',
        pointnum2: '2',
        point2: 'Complete Solution',
        point2content: ' to ensure that all solid waste generated at your business is collected and managed in time.',
        pointnum3: '3',
        point3: 'Quality standards',
        point3content: ' are important but meant to be exceeded',
        pointnum4: '4',
        point4: 'We are always looking',

        point4content: ' for industry leaders to help them win their market position.',
        pointnum5: '5',
        point5: 'Evaluation',
        point5content: ' is a key aspect of this business and important.',
        pointnum6: '6',
        point6: 'Ethic',
        point6content: ' procedures are always at the base of everything we do.',

        home: 'Home',
        point1content1: 'We strive to make',
        point1content2: ' waste management accessible for all the parts of the valley',
        point2content1: 'Our goal is to help',
        point2content2: ' bridge the gap between communities, waste management authorities, and recyling authorities.',
        list1: 'It is easy to get a trashcan placed at your location, just give us a call.',
        list2: 'We will also install the system to your local waste collecting authority.',
        list3: 'We have tested our hardware to their limits ensuring the best final product at your community.'
    },
    team: {
        header: 'Our Team Of Consultants',
        headercontent: 'We are only as strong and as knowledgeable as our team. So here are the men and women helping us achieve our goals.',
        prabin: 'Prabin Thapaliya',
        post1: 'General Manager',
        pragya: 'Pragya Thapaliya',
        post2: 'Chief Strategist',
        suson: 'Suson Sapkota',
        post3: 'System Consultant',
        pratik: 'Pratik Karki',
        post4: 'System Designer',
        kshitiz: 'Kshitiz Mainali',
        post5: 'Business Analyst',
        riwaj: 'Riwaj Lama',
        post6: 'Designer',
        jasmine: 'Jasmine Praween',
        post7: 'Flutter Developer'
    },
    about:{
        header: 'ABOUT',
        content: 'We are Passionate About Doing Our Part To Help Clean The City',
        subcontent: 'Our goal is to provide the right tools which can can go on to restore Kathmandu to its glory. ',
        point1: 'Everything we recommend has direct positive impact',
        point2: 'You will become an important partner of our company',
        happy: 'Happy',
        users: 'Users',
        issues: 'Issues',
        solved: 'Solved',
        good: 'Good',
        reviews: 'Reviews'
    },
    contact: {
        header: 'CONTACT',
        content: 'Get In Touch Using The Form',
        subcontent: 'You can stop by our office for a cup of coffee and just use the contact form below for any questions and inquiries',
        location: '44602, Hadigaun, Kathmandu, Nepal',
        mobile: '+977 9813946968',
        landline: '+977 01 4009718',
        email: 'prabinth13@gmail.com',
        social: 'Follow Fohor Malai On Social Media',
        name: 'Name',
        email2: 'Email',
        message: 'Your Message',
        agreement: 'I agree with ',
        policy: 'Privacy Policy',
        and: 'and',
        conditions: 'Terms Conditions',
        submit: 'SUBMIT MESSAGE'

    }
};
